config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :guests
  resources :people
  

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	/validates :name, :email, :adult, :child, presence: true
	validates :attend, inclusion: { in: [true, false] }/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

	def new
		@guest = Guest.new
	end

	def create
		#render plain: params[:guest].inspect
		@guest = Guest.new(guest_params)
		@guest.save
	end
	
	def index
		@guests = Guest.all
	end
	
	def show
		
	end
	
	private 
		def guest_params	
			params.require(:guest).permit(:name, :email, :attend, :adult, :child)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guests/create.html.erb
<div class="topsquare">
<h2>
Thank you, 
<%= @guest.name %>
</h2>


</div>

<div class="mapdiv">
<h3>
	4th December 2016 4:00pm onwards
</h3>

<iframe
	
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCrvbvuOIFzG4yGLfCwKs5NsOR89LsPpZI
    &q=6020 Yucca Lane N, Plymouth MN 55446" allowfullscreen>
</iframe>

</div>

app/views/guests/index.html.erb
<h1>Listing all guests</h1>

<table>
	<tr>
		<th>Guest Name</th>
		<th>Email</th>
		<th>Is guest attending the party</th>
		<th>Number of Adults</th>
		<th>Number of kids</th>
	</tr>
	
	<% @guests.each do |guest| %>
		<tr>
			<td><%= guest.name %></td>
			<td><%= guest.email %></td>
			<td><%= guest.attend %></td>
			<td><%= guest.adult %></td>
			<td><%= guest.child %></td>
		</tr>
	<% end %>
</table>

app/views/guests/new.html.erb
<div class="topsquare">
	<h1> Aanaya's First Birthday Party </h1>
	<h2> 
		<ul>
			<li>4th December 2016</li> 
			<li>4:00pm</li>
			<li>6020 Yucca Lane N, Plymouth 55446</li>
		</ul>
	</h2>
</div>

<div class="birthday">
<%= form_for :guest, url: guests_path do |f| %>
	
<% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@guest.errors.count, "error") %> prohibited
        this guest from being saved:
      </h2>
      <ul>
        <% @guest.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
	
		<!-- <%= f.label :name %> -->
		<%= f.text_field :name, placeholder: "Name" %>
	<br><br>
	
	
		<!-- <%= f.label :email %>  -->
		<%= f.text_field :email, placeholder: "Email" %>
	<br><br>
	
	
		<%= f.radio_button(:attend, "willattend") %>
		<%= f.label(:attend_willattend, "I will attend!!!") %>
		<br>
		<%= f.radio_button(:attend, "raincheck") %>
		<%= f.label(:attend_raincheck, "Raincheck???") %>
		
	<br><br>
	
	

		<!-- <%= f.label :adult, "No of Adults - " %>  -->
		<%= f.number_field :adult, placeholder: "No of Adults (Please include yourself)" %> <br><br>
		<!-- <%= f.label :child, "No of kids - " %>  -->
		<%= f.number_field :child, placeholder: "No of Kids" %><br>

	<br>
		
		<%= f.submit %>
	<br><br>
	
<% end %>

<!-- <%= link_to 'List all guests', guests_path %>	-->	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BdayApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h2>BDay App<h2>